# Generated by Django 2.2.1 on 2019-05-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190527_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='waktu_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
