# Generated by Django 2.2.1 on 2019-05-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id_penjualan', models.AutoField(primary_key=True, serialize=False)),
                ('bulan_transaksi', models.CharField(max_length=255)),
                ('tahun_transaksi', models.CharField(max_length=255)),
                ('jumlah_hotel', models.IntegerField()),
                ('jumlah_mall', models.IntegerField()),
                ('jumlah_apartemen', models.IntegerField()),
                ('jumlah_C441', models.IntegerField()),
                ('jumlah_C442', models.IntegerField()),
                ('jumlah_C443', models.IntegerField()),
                ('jumlah_C451', models.IntegerField()),
                ('jumlah_C452', models.IntegerField()),
                ('jumlah_C453', models.IntegerField()),
                ('jumlah_C461', models.IntegerField()),
                ('jumlah_C462', models.IntegerField()),
                ('jumlah_C463', models.IntegerField()),
                ('jasa_pembersih_air', models.IntegerField()),
                ('jasa_pembersih_kerak_sillica', models.IntegerField()),
                ('jasa_pembersih_cooling_tower', models.IntegerField()),
                ('jasa_pembersih_stp', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
